sudo: required

group: travis_lts

services:
  - docker

languages: node_js

node_js:
  - "8"

install:
  docker build -t citegen:latest .

script:
  - docker run -it --rm citegen:latest make unit-test
  - docker run -it --rm citegen:latest make integration-test
