sudo: required

group: travis_lts

services:
  - docker

languages: node_js

node_js:
  - "8"

install:
  - make build-docker
  - make start-docker
  - docker exec citegen-dev-box yarn

script:
  - make test

after_script:
  - make stop-docker
