sudo: required

group: travis_lts

services:
  - docker

language: node_js

node_js:
  - "8"

install:
  - docker pull customcommander/citegen-dev
  - make start-docker
  - docker exec citegen-dev-box yarn

script:
  - make build
  - make test

after_script:
  - make stop-docker
